# Generated by Django 3.2 on 2021-04-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinasiWisataYogyakarta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='telephone',
        ),
    ]
